services:
  - type: web
    name: tiff2geojson-server
    runtime: docker
    env: python
    build:
      dockerfile: Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tiff2geojson-db
          property: connectionString
      - key: ADMIN_TOKEN
        generateValue: true
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: tiff2geojson-db
    databaseName: tiff2geojson
    user: tiff2geojson_user
    plan: free